using System.Collections.Generic;
using System.IO;
using System.Linq;

using UnityEditor;

using UnityEngine;

namespace Kiwi.Utility.Editor
{
	/// <summary>
	/// Editor Icons 浏览器
	/// </summary>
	/// <remarks>网上找到的代码, 但是忘了原地址了.</remarks>
	public class EditorIconsBrowser : EditorWindow
	{
		[ EditorToolbar(EditorToolbarAttribute.Anchor.Right , "Kiwi" , "浏览器/Editor Icons 浏览器") ]
		public static void Open()
		{
			var window = CreateWindow<EditorIconsBrowser>("Editor Icons 浏览器");
			window.ShowUtility();
			window.minSize = new(550 , 450);
		}

		/// <summary>
		/// 是否为大图标显示
		/// </summary>
		private static bool _viewBigIcons = true;

		/// <summary>
		/// 滚动窗位置
		/// </summary>
		private Vector2 _scrollPosition;

		/// <summary>
		/// 图标按钮尺寸
		/// </summary>
		private int _buttonSize = 70;

		/// <summary>
		/// 搜索内容
		/// </summary>
		private string _search = "";

		/// <summary>
		/// 搜索框 GUI
		/// </summary>
		private void SearchGUI()
		{
			_search = EditorGUILayout.TextField(_search , EditorStyles.toolbarSearchField);

			if (!string.IsNullOrEmpty(_search))
				if (GUILayout.Button(EditorGUIUtility.IconContent("d_winbtn_win_close") , "ToolbarSearchCancelButton"))
					_search = string.Empty;
		}

		/// <summary>
		/// 是否正在搜索
		/// </summary>
		private bool doSearch => !string.IsNullOrEmpty(_search);

		/// <summary>
		/// 获取 Icon GUIContent
		/// </summary>
		/// <param name="name">Icon 名称</param>
		/// <returns></returns>
		private static GUIContent GetIcon(string name)
		{
			GUIContent valid = null;
			Debug.unityLogger.logEnabled = false;
			if (!string.IsNullOrEmpty(name)) valid = EditorGUIUtility.IconContent(name);
			Debug.unityLogger.logEnabled = true;

			return valid?.image == null ? null : valid;
		}

		/// <summary>
		/// 保存 Icon
		/// </summary>
		/// <param name="name"></param>
		private static void SaveIcon(string name)
		{
			var tex2D = EditorGUIUtility.IconContent(name).image as Texture2D;

			if (tex2D != null)
			{
				var path = EditorUtility.SaveFilePanel("Save icon" , string.Empty , name , "png");

				if (path != null)
				{
					try
					{
						var outTex = new Texture2D(
							tex2D.width , tex2D.height ,
							tex2D.format , tex2D.mipmapCount , true);

						Graphics.CopyTexture(tex2D , outTex);

						File.WriteAllBytes(path , outTex.EncodeToPNG());
					}
					catch (System.Exception e)
					{
						Debug.LogError("保存Icon失败 : " + e.Message);
					}
				}
			}
			else
			{
				Debug.LogError("保存Icon失败 : null texture");
			}
		}

		private void OnEnable()
		{
			var all_icons = IconList.Where(x => GetIcon(x) != null);
			var unique    = new List<string>();

			foreach (var x in Resources.FindObjectsOfTypeAll<Texture2D>())
			{
				GUIContent icoContent = GetIcon(x.name);

				if (icoContent == null) continue;

				if (!all_icons.Contains(x.name))
				{
					unique.Add(x.name);
				}
			}

			Resources.UnloadUnusedAssets();
			System.GC.Collect();
		}

		private void OnGUI()
		{
			var ppp = EditorGUIUtility.pixelsPerPoint;

			InitIcons();

			using (new GUILayout.HorizontalScope(EditorStyles.toolbar))
			{
				_viewBigIcons = GUILayout.SelectionGrid(
						_viewBigIcons ? 1 : 0 , new[ ]
						                        {
							                        "小图标" ,
							                        "大图标"
						                        } ,
						2 , EditorStyles.toolbarButton)
				 == 1;

				SearchGUI();
			}

			using (var scope = new GUILayout.ScrollViewScope(_scrollPosition))
			{
				GUILayout.Space(10);

				_scrollPosition = scope.scrollPosition;

				_buttonSize = _viewBigIcons ? 70 : 40;

				var render_width = Screen.width / ppp - 13f;
				var gridW        = Mathf.FloorToInt(render_width / _buttonSize);
				var margin_left  = (render_width - _buttonSize * gridW) / 2;

				int row = 0 , index = 0;

				List<GUIContent> iconList;

				if (doSearch)
					iconList = iconContentListAll.Where(x => x.tooltip.ToLower()
					                                          .Contains(_search.ToLower()))
					                             .ToList();
				else iconList = _viewBigIcons ? iconContentListBig : iconContentListSmall;

				while (index < iconList.Count)
				{
					using (new GUILayout.HorizontalScope())
					{
						GUILayout.Space(margin_left);

						for (var i = 0 ; i < gridW ; ++i)
						{
							int k = i + row * gridW;

							var icon = iconList[k];

							if (GUILayout.Button(icon ,
							                     iconButtonStyle ,
							                     GUILayout.Width(_buttonSize) ,
							                     GUILayout.Height(_buttonSize)))
							{
								EditorGUI.FocusTextInControl("");
								iconSelected = icon;
							}

							index++;

							if (index == iconList.Count) break;
						}
					}

					row++;
				}

				GUILayout.Space(10);
			}


			if (iconSelected == null) return;

			GUILayout.FlexibleSpace();

			using (new GUILayout.HorizontalScope(EditorStyles.helpBox , GUILayout.MaxHeight(_viewBigIcons ? 140 : 120)))
			{
				using (new GUILayout.VerticalScope(GUILayout.Width(130)))
				{
					GUILayout.Space(2);

					GUILayout.Button(iconSelected , iconPreview ,
					                 GUILayout.Width(128) , GUILayout.Height(128));

					GUILayout.FlexibleSpace();
				}

				GUILayout.Space(10);

				using (new GUILayout.VerticalScope())
				{
					var s = $"尺寸: {iconSelected.image.width}x{iconSelected.image.height}";
					s += "\n专业版图标: " + (iconSelected.tooltip.IndexOf("d_") == 0 ? "是" : "否");
					s += $"\n总共 {iconContentListAll.Count} 个图标";
					GUILayout.Space(5);
					EditorGUILayout.HelpBox(s , MessageType.None);
					GUILayout.Space(5);
					EditorGUILayout.TextField("EditorGUIUtility.IconContent(\"" + iconSelected.tooltip + "\")");
					GUILayout.Space(5);

					if (GUILayout.Button("复制到剪贴板" , EditorStyles.miniButton))
						EditorGUIUtility.systemCopyBuffer = iconSelected.tooltip;

					if (GUILayout.Button("保存成文件" , EditorStyles.miniButton))
						SaveIcon(iconSelected.tooltip);
				}

				GUILayout.Space(10);

				if (GUILayout.Button(EditorGUIUtility.IconContent("winbtn_win_close_h") , GUIStyle.none , GUILayout.Width(16)))
				{
					iconSelected = null;
				}
			}
		}

		static GUIContent iconSelected;
		static List<GUIContent> iconContentListAll;
		static List<GUIContent> iconContentListSmall;
		static List<GUIContent> iconContentListBig;
		static List<string> iconMissingNames;
		static GUIStyle iconButtonStyle = null;
		static GUIStyle iconPreview = null;

		void InitIcons()
		{
			if (iconContentListSmall != null) return;

			iconButtonStyle = new(EditorStyles.miniButton)
			                  {
				                  margin      = new(0 , 0 , 0 , 0) ,
				                  fixedHeight = 0 ,
			                  };

			iconPreview = new(iconButtonStyle);

			iconMissingNames     = new();
			iconContentListSmall = new();
			iconContentListBig   = new();
			iconContentListAll   = new();

			for (var i = 0 ; i < IconList.Length ; ++i)
			{
				GUIContent ico = GetIcon(IconList[i]);

				if (ico == null)
				{
					iconMissingNames.Add(IconList[i]);

					continue;
				}

				ico.tooltip = IconList[i];

				iconContentListAll.Add(ico);

				if (!(ico.image.width <= 36 || ico.image.height <= 36))
					iconContentListBig.Add(ico);
				else iconContentListSmall.Add(ico);
			}
		}

		// https://gist.github.com/MattRix/c1f7840ae2419d8eb2ec0695448d4321
		// https://unitylist.com/p/5c3/Unity-editor-icons

		#region ICONS

		private static readonly string[ ] IconList =
		{
			"_Help" ,
			"_Popup" ,
			"aboutwindow.mainheader" ,
			"AboutWindow.MainHeader" ,
			"ageialogo" ,
			"AgeiaLogo" ,
			"AimConstraint Icon" ,
			"align_horizontally" ,
			"align_horizontally_center" ,
			"align_horizontally_center_active" ,
			"align_horizontally_left" ,
			"align_horizontally_left_active" ,
			"align_horizontally_right" ,
			"align_horizontally_right_active" ,
			"align_vertically" ,
			"align_vertically_bottom" ,
			"align_vertically_bottom_active" ,
			"align_vertically_center" ,
			"align_vertically_center_active" ,
			"align_vertically_top" ,
			"align_vertically_top_active" ,
			"AlphabeticalSorting" ,
			"AnalyticsTracker Icon" ,
			"AnchorBehaviour Icon" ,
			"AnchorInputListenerBehaviour Icon" ,
			"AnchorStageBehaviour Icon" ,
			"Animation Icon" ,
			"Animation.AddEvent" ,
			"Animation.AddKeyframe" ,
			"Animation.EventMarker" ,
			"Animation.FirstKey" ,
			"Animation.LastKey" ,
			"Animation.NextKey" ,
			"Animation.Play" ,
			"Animation.PrevKey" ,
			"Animation.Record" ,
			"Animation.SequencerLink" ,
			"animationanimated" ,
			"AnimationClip Icon" ,
			"animationdopesheetkeyframe" ,
			"animationkeyframe" ,
			"animationnocurve" ,
			"AnimationRowEven" ,
			"AnimationRowEven@2x" ,
			"AnimationRowEvenSelected" ,
			"AnimationRowEvenSelected@2x" ,
			"AnimationRowEvenSemiSelected" ,
			"AnimationRowEvenSemiSelected@2x" ,
			"AnimationRowOdd" ,
			"AnimationRowOdd@2x" ,
			"AnimationRowOddSelected" ,
			"AnimationRowOddSelected@2x" ,
			"AnimationRowOddSemiSelected" ,
			"AnimationRowOddSemiSelected@2x" ,
			"animationvisibilitytoggleoff" ,
			"animationvisibilitytoggleon" ,
			"AnimationWindowEvent Icon" ,
			"AnimationWrapModeMenu" ,
			"Animator Icon" ,
			"AnimatorController Icon" ,
			"AnimatorOverrideController Icon" ,
			"AnimatorState Icon" ,
			"AnimatorStateMachine Icon" ,
			"AnimatorStateTransition Icon" ,
			"AnyStateNode Icon" ,
			"AreaEffector2D Icon" ,
			"AreaLight Gizmo" ,
			"AreaLight Icon" ,
			"Arial Atlas" ,
			"Arial Unicode Atlas" ,
			"ArrowNavigationLeft" ,
			"ArrowNavigationLeft@2x" ,
			"ArrowNavigationRight" ,
			"ArrowNavigationRight@2x" ,
			"AS Badge Delete" ,
			"AS Badge Move" ,
			"AS Badge New" ,
			"AspectRatioFitter Icon" ,
			"Assembly Icon" ,
			"AssemblyDefinitionAsset Icon" ,
			"AssemblyLock" ,
			"Asset Store" ,
			"AssetLabelIcon" ,
			"AssetLabelIcon@2x" ,
			"AssetStore Icon" ,
			"Audio Mixer" ,
			"AudioChorusFilter Icon" ,
			"AudioClip Icon" ,
			"AudioDistortionFilter Icon" ,
			"AudioEchoFilter Icon" ,
			"AudioHighPassFilter Icon" ,
			"AudioListener Icon" ,
			"AudioLowPassFilter Icon" ,
			"AudioMixerController Icon" ,
			"AudioMixerGroup Icon" ,
			"AudioMixerSnapshot Icon" ,
			"AudioMixerView Icon" ,
			"AudioReverbFilter Icon" ,
			"AudioReverbZone Icon" ,
			"AudioSource Gizmo" ,
			"AudioSource Icon" ,
			"AudioSpatializerMicrosoft Icon" ,
			"Avatar Icon" ,
			"AvatarCompass" ,
			"AvatarController.Layer" ,
			"AvatarController.LayerHover" ,
			"AvatarController.LayerSelected" ,
			"AvatarInspector/BodyPartPicker" ,
			"AvatarInspector/BodySilhouette" ,
			"AvatarInspector/BodySIlhouette" ,
			"AvatarInspector/DotFill" ,
			"AvatarInspector/DotFrame" ,
			"AvatarInspector/DotFrameDotted" ,
			"AvatarInspector/DotSelection" ,
			"AvatarInspector/Head" ,
			"AvatarInspector/HeadZoom" ,
			"AvatarInspector/HeadZoomSilhouette" ,
			"AvatarInspector/LeftArm" ,
			"AvatarInspector/LeftFeetIk" ,
			"AvatarInspector/LeftFingers" ,
			"AvatarInspector/LeftFingersIk" ,
			"AvatarInspector/LeftHandZoom" ,
			"AvatarInspector/LeftHandZoomSilhouette" ,
			"AvatarInspector/LeftLeg" ,
			"AvatarInspector/MaskEditor_Root" ,
			"AvatarInspector/RightArm" ,
			"AvatarInspector/RightFeetIk" ,
			"AvatarInspector/RightFingers" ,
			"AvatarInspector/RightFingersIk" ,
			"AvatarInspector/RightHandZoom" ,
			"AvatarInspector/RightHandZoomSilhouette" ,
			"AvatarInspector/RightLeg" ,
			"AvatarInspector/Torso" ,
			"AvatarMask Icon" ,
			"AvatarPivot" ,
			"back" ,
			"back@2x" ,
			"beginButton" ,
			"beginButton-On" ,
			"bg_HeaderCollapsed@2x" ,
			"bg_HeaderExpanded@2x" ,
			"BillboardAsset Icon" ,
			"BillboardRenderer Icon" ,
			"blendKey" ,
			"blendKeyOverlay" ,
			"blendKeySelected" ,
			"blendSampler" ,
			"BlendTree Icon" ,
			"blueGroove" ,
			"BodyPartPicker" ,
			"BodySilhouette" ,
			"boo Script Icon" ,
			"box" ,
			"box@2x" ,
			"BoxCollider Icon" ,
			"BoxCollider2D Icon" ,
			"btn" ,
			"btn act" ,
			"btn act@2x" ,
			"btn focus" ,
			"btn focus@2x" ,
			"btn left" ,
			"btn left act" ,
			"btn left act@2x" ,
			"btn left focus" ,
			"btn left focus@2x" ,
			"btn left on" ,
			"btn left on focus" ,
			"btn left on focus@2x" ,
			"btn left on@2x" ,
			"btn left onact" ,
			"btn left onact@2x" ,
			"btn left@2x" ,
			"btn mid" ,
			"btn mid act" ,
			"btn mid act@2x" ,
			"btn mid focus" ,
			"btn mid focus@2x" ,
			"btn mid on" ,
			"btn mid on focus" ,
			"btn mid on@2x" ,
			"btn mid onact" ,
			"btn mid onact@2x" ,
			"btn mid@2x" ,
			"btn on" ,
			"btn on focus" ,
			"btn on focus@2x" ,
			"btn on@2x" ,
			"btn onact" ,
			"btn onact@2x" ,
			"btn right" ,
			"btn right act" ,
			"btn right act@2x" ,
			"btn right focus" ,
			"btn right focus@2x" ,
			"btn right on" ,
			"btn right on focus" ,
			"btn right on focus@2x" ,
			"btn right on@2x" ,
			"btn right onact" ,
			"btn right onact@2x" ,
			"btn right@2x" ,
			"btn@2x" ,
			"BuildSettings.Android" ,
			"BuildSettings.Android.Small" ,
			"BuildSettings.BlackBerry" ,
			"BuildSettings.BlackBerry.Small" ,
			"BuildSettings.Broadcom" ,
			"BuildSettings.Editor" ,
			"BuildSettings.Editor.Small" ,
			"BuildSettings.Facebook" ,
			"BuildSettings.Facebook.Small" ,
			"BuildSettings.FlashPlayer" ,
			"BuildSettings.FlashPlayer.Small" ,
			"BuildSettings.iPhone" ,
			"BuildSettings.iPhone.Small" ,
			"BuildSettings.Lumin" ,
			"BuildSettings.Lumin.small" ,
			"BuildSettings.Metro" ,
			"BuildSettings.Metro.Small" ,
			"BuildSettings.N3DS" ,
			"BuildSettings.N3DS.Small" ,
			"BuildSettings.PS3" ,
			"BuildSettings.PS3.Small" ,
			"BuildSettings.PS4" ,
			"BuildSettings.PS4.Small" ,
			"BuildSettings.PSM" ,
			"BuildSettings.PSM.Small" ,
			"BuildSettings.PSP2" ,
			"BuildSettings.PSP2.Small" ,
			"BuildSettings.SamsungTV" ,
			"BuildSettings.SamsungTV.Small" ,
			"BuildSettings.SelectedIcon" ,
			"BuildSettings.Standalone" ,
			"BuildSettings.Standalone.Small" ,
			"BuildSettings.StandaloneBroadcom.Small" ,
			"BuildSettings.StandaloneGLES20Emu.Small" ,
			"BuildSettings.StandaloneGLESEmu" ,
			"BuildSettings.StandaloneGLESEmu.Small" ,
			"BuildSettings.Switch" ,
			"BuildSettings.Switch.Small" ,
			"BuildSettings.Tizen" ,
			"BuildSettings.Tizen.Small" ,
			"BuildSettings.tvOS" ,
			"BuildSettings.tvOS.Small" ,
			"BuildSettings.Web" ,
			"BuildSettings.Web.Small" ,
			"BuildSettings.WebGL" ,
			"BuildSettings.WebGL.Small" ,
			"BuildSettings.WP8" ,
			"BuildSettings.WP8.Small" ,
			"BuildSettings.Xbox360" ,
			"BuildSettings.XBox360" ,
			"BuildSettings.Xbox360.Small" ,
			"BuildSettings.XBox360.Small" ,
			"BuildSettings.XboxOne" ,
			"BuildSettings.XboxOne.Small" ,
			"BuildSettings.Xiaomi" ,
			"BuoyancyEffector2D Icon" ,
			"Button Icon" ,
			"buttonpulldown act" ,
			"buttonpulldown act@2x" ,
			"buttonpulldown@2x" ,
			"Camera Gizmo" ,
			"Camera Icon" ,
			"Canvas Icon" ,
			"CanvasGroup Icon" ,
			"CanvasRenderer Icon" ,
			"CanvasScaler Icon" ,
			"CapsuleCollider Icon" ,
			"CapsuleCollider2D Icon" ,
			"CGProgram Icon" ,
			"CharacterController Icon" ,
			"CharacterJoint Icon" ,
			"CheckerFloor" ,
			"ChorusFilter Icon" ,
			"CircleCollider2D Icon" ,
			"Clipboard" ,
			"Cloth Icon" ,
			"ClothInspector.PaintTool" ,
			"ClothInspector.PaintValue" ,
			"ClothInspector.SelectTool" ,
			"ClothInspector.SettingsTool" ,
			"ClothInspector.ViewValue" ,
			"CloudConnect" ,
			"CloudRecoBehaviour Icon" ,
			"cmd" ,
			"cmd act" ,
			"cmd act@2x" ,
			"cmd focus" ,
			"cmd focus@2x" ,
			"cmd left" ,
			"cmd left act" ,
			"cmd left act@2x" ,
			"cmd left focus" ,
			"cmd left focus@2x" ,
			"cmd left on" ,
			"cmd left on focus" ,
			"cmd left on focus@2x" ,
			"cmd left on@2x" ,
			"cmd left onact" ,
			"cmd left onact@2x" ,
			"cmd left@2x" ,
			"cmd mid" ,
			"cmd mid act" ,
			"cmd mid act@2x" ,
			"cmd mid focus" ,
			"cmd mid focus@2x" ,
			"cmd mid on" ,
			"cmd mid on@2x" ,
			"cmd mid onact" ,
			"cmd mid onact@2x" ,
			"cmd mid@2x" ,
			"cmd on" ,
			"cmd on focus" ,
			"cmd on focus@2x" ,
			"cmd on@2x" ,
			"cmd onact" ,
			"cmd onact@2x" ,
			"cmd right" ,
			"cmd right act" ,
			"cmd right act@2x" ,
			"cmd right focus" ,
			"cmd right focus@2x" ,
			"cmd right on" ,
			"cmd right on focus" ,
			"cmd right on focus@2x" ,
			"cmd right on@2x" ,
			"cmd right onact" ,
			"cmd right onact@2x" ,
			"cmd right@2x" ,
			"cmd@2x" ,
			"cn entrybackodd" ,
			"cn entrybackodd@2x" ,
			"cnentrybackeven" ,
			"cnentrybackeven@2x" ,
			"Collab" ,
			"Collab.Build" ,
			"Collab.BuildFailed" ,
			"Collab.BuildSucceeded" ,
			"Collab.FileAdded" ,
			"Collab.FileConflict" ,
			"Collab.FileDeleted" ,
			"Collab.FileIgnored" ,
			"Collab.FileMoved" ,
			"Collab.FileUpdated" ,
			"Collab.FolderAdded" ,
			"Collab.FolderConflict" ,
			"Collab.FolderDeleted" ,
			"Collab.FolderIgnored" ,
			"Collab.FolderMoved" ,
			"Collab.FolderUpdated" ,
			"Collab.NoInternet" ,
			"Collab.Warning" ,
			"CollabChanges Icon" ,
			"CollabChangesConflict Icon" ,
			"CollabChangesDeleted Icon" ,
			"CollabConflict" ,
			"CollabConflict Icon" ,
			"CollabCreate Icon" ,
			"CollabDeleted Icon" ,
			"CollabEdit Icon" ,
			"CollabError" ,
			"CollabExclude Icon" ,
			"CollabMoved Icon" ,
			"CollabNew" ,
			"CollabOffline" ,
			"CollabProgress" ,
			"CollabPull" ,
			"CollabPush" ,
			"ColorField focus" ,
			"ColorField focus@2x" ,
			"ColorField@2x" ,
			"ColorPicker.ColorCycle" ,
			"ColorPicker.CycleColor" ,
			"ColorPicker.CycleSlider" ,
			"ColorPicker.SliderCycle" ,
			"colorpickerbox" ,
			"colorpickerbox@2x" ,
			"colorpickerboxfocused" ,
			"colorpickerboxfocused@2x" ,
			"com.unity.visualscripting.blockDebugBox" ,
			"com.unity.visualscripting.labelDebugBox" ,
			"CompositeCollider2D Icon" ,
			"ComputeShader Icon" ,
			"ConfigurableJoint Icon" ,
			"console.erroricon" ,
			"console.erroricon.inactive.sml" ,
			"console.erroricon.sml" ,
			"console.infoicon" ,
			"console.infoicon.sml" ,
			"console.warnicon" ,
			"console.warnicon.inactive.sml" ,
			"console.warnicon.sml" ,
			"ConstantForce Icon" ,
			"ConstantForce2D Icon" ,
			"ContentPlacementBehaviour Icon" ,
			"ContentPositioningBehaviour Icon" ,
			"ContentSizeFitter Icon" ,
			"cs Script Icon" ,
			"Cubemap Icon" ,
			"curvekeyframe" ,
			"curvekeyframeselected" ,
			"curvekeyframeselectedoverlay" ,
			"curvekeyframesemiselectedoverlay" ,
			"curvekeyframeweighted" ,
			"CustomSorting" ,
			"CylinderTargetBehaviour Icon" ,
			"d__Help@2x" ,
			"d__Menu@2x" ,
			"d__Popup" ,
			"d__Popup@2x" ,
			"d_aboutwindow.mainheader" ,
			"d_account" ,
			"d_account@2x" ,
			"d_ageialogo" ,
			"d_AimConstraint Icon" ,
			"d_align_horizontally" ,
			"d_align_horizontally_center" ,
			"d_align_horizontally_center_active" ,
			"d_align_horizontally_left" ,
			"d_align_horizontally_left_active" ,
			"d_align_horizontally_right" ,
			"d_align_horizontally_right_active" ,
			"d_align_vertically" ,
			"d_align_vertically_bottom" ,
			"d_align_vertically_bottom_active" ,
			"d_align_vertically_center" ,
			"d_align_vertically_center_active" ,
			"d_align_vertically_top" ,
			"d_align_vertically_top_active" ,
			"d_AlphabeticalSorting" ,
			"d_AnchorBehaviour Icon" ,
			"d_AnchorInputListenerBehaviour Icon" ,
			"d_AnchorStageBehaviour Icon" ,
			"d_Animation.AddEvent" ,
			"d_Animation.AddKeyframe" ,
			"d_Animation.EventMarker" ,
			"d_Animation.FirstKey" ,
			"d_Animation.LastKey" ,
			"d_Animation.NextKey" ,
			"d_Animation.Play" ,
			"d_Animation.PrevKey" ,
			"d_Animation.Record" ,
			"d_Animation.SequencerLink" ,
			"d_animationanimated" ,
			"d_animationkeyframe" ,
			"d_animationnocurve" ,
			"d_animationvisibilitytoggleoff" ,
			"d_animationvisibilitytoggleon" ,
			"d_AnimationWrapModeMenu" ,
			"d_AS Badge Delete" ,
			"d_AS Badge New" ,
			"d_AspectRatioFitter Icon" ,
			"d_AssemblyDefinitionAsset Icon" ,
			"d_AssemblyLock" ,
			"d_Asset Store" ,
			"d_AssetStore Icon" ,
			"d_Audio Mixer" ,
			"d_AudioMixerView Icon" ,
			"d_AutoLightbakingOff@2x" ,
			"d_AutoLightbakingOn@2x" ,
			"d_AvatarBlendBackground" ,
			"d_AvatarBlendLeft" ,
			"d_AvatarBlendLeftA" ,
			"d_AvatarBlendRight" ,
			"d_AvatarBlendRightA" ,
			"d_AvatarCompass" ,
			"d_AvatarPivot" ,
			"d_back" ,
			"d_back@2x" ,
			"d_beginButton" ,
			"d_beginButton-On" ,
			"d_blueGroove" ,
			"d_BuildSettings.Android" ,
			"d_BuildSettings.Android.Small" ,
			"d_BuildSettings.Broadcom" ,
			"d_BuildSettings.FlashPlayer" ,
			"d_BuildSettings.FlashPlayer.Small" ,
			"d_BuildSettings.iPhone" ,
			"d_BuildSettings.iPhone.Small" ,
			"d_BuildSettings.Lumin" ,
			"d_BuildSettings.Lumin.small" ,
			"d_BuildSettings.PS4" ,
			"d_BuildSettings.PS4.Small" ,
			"d_BuildSettings.PSP2" ,
			"d_BuildSettings.PSP2.Small" ,
			"d_BuildSettings.SelectedIcon" ,
			"d_BuildSettings.Standalone" ,
			"d_BuildSettings.Standalone.Small" ,
			"d_BuildSettings.tvOS" ,
			"d_BuildSettings.tvOS.Small" ,
			"d_BuildSettings.Web" ,
			"d_BuildSettings.Web.Small" ,
			"d_BuildSettings.WebGL" ,
			"d_BuildSettings.WebGL.Small" ,
			"d_BuildSettings.Xbox360" ,
			"d_BuildSettings.Xbox360.Small" ,
			"d_BuildSettings.XboxOne" ,
			"d_BuildSettings.XboxOne.Small" ,
			"d_CacheServerConnected@2x" ,
			"d_CacheServerDisabled@2x" ,
			"d_CacheServerDisconnected@2x" ,
			"d_Canvas Icon" ,
			"d_CanvasGroup Icon" ,
			"d_CanvasRenderer Icon" ,
			"d_CanvasScaler Icon" ,
			"d_CheckerFloor" ,
			"d_checkmark" ,
			"d_clear" ,
			"d_clear@2x" ,
			"d_clear_uielements" ,
			"d_clear_uielements@2x" ,
			"d_CloudConnect" ,
			"d_CloudConnect@2x" ,
			"d_CloudRecoBehaviour Icon" ,
			"d_Collab.FileAdded" ,
			"d_Collab.FileConflict" ,
			"d_Collab.FileDeleted" ,
			"d_Collab.FileIgnored" ,
			"d_Collab.FileMoved" ,
			"d_Collab.FileUpdated" ,
			"d_Collab.FolderAdded" ,
			"d_Collab.FolderConflict" ,
			"d_Collab.FolderDeleted" ,
			"d_Collab.FolderIgnored" ,
			"d_Collab.FolderMoved" ,
			"d_Collab.FolderUpdated" ,
			"d_CollabChanges Icon" ,
			"d_CollabChangesConflict Icon" ,
			"d_CollabChangesDeleted Icon" ,
			"d_CollabConflict Icon" ,
			"d_CollabCreate Icon" ,
			"d_CollabDeleted Icon" ,
			"d_CollabEdit Icon" ,
			"d_CollabExclude Icon" ,
			"d_CollabMoved Icon" ,
			"d_color_picker" ,
			"d_color_picker@2x" ,
			"d_ColorPicker.CycleColor" ,
			"d_ColorPicker.CycleSlider" ,
			"d_console.erroricon" ,
			"d_console.erroricon.inactive.sml@2x" ,
			"d_console.erroricon.sml" ,
			"d_console.erroricon.sml@2x" ,
			"d_console.erroricon@2x" ,
			"d_console.infoicon" ,
			"d_console.infoicon.inactive.sml@2x" ,
			"d_console.infoicon.sml" ,
			"d_console.infoicon.sml@2x" ,
			"d_console.infoicon@2x" ,
			"d_console.warnicon" ,
			"d_console.warnicon.inactive.sml@2x" ,
			"d_console.warnicon.sml" ,
			"d_console.warnicon.sml@2x" ,
			"d_console.warnicon@2x" ,
			"d_ContentPlacementBehaviour Icon" ,
			"d_ContentPositioningBehaviour Icon" ,
			"d_ContentSizeFitter Icon" ,
			"d_CreateAddNew@2x" ,
			"d_cs Script Icon" ,
			"d_curvekeyframe" ,
			"d_curvekeyframeselected" ,
			"d_curvekeyframeselectedoverlay" ,
			"d_curvekeyframesemiselectedoverlay" ,
			"d_curvekeyframeweighted" ,
			"d_CustomSorting" ,
			"d_CustomTool@2x" ,
			"d_CylinderTargetBehaviour Icon" ,
			"d_DataMode.Authoring.Sticky@2x" ,
			"d_DataMode.Authoring@2x" ,
			"d_DataMode.Mixed.Sticky@2x" ,
			"d_DataMode.Mixed@2x" ,
			"d_DataMode.Runtime.Sticky@2x" ,
			"d_DataMode.Runtime@2x" ,
			"d_DebuggerAttached@2x" ,
			"d_DebuggerDisabled@2x" ,
			"d_DebuggerEnabled@2x" ,
			"d_DefaultAsset Icon" ,
			"d_DefaultSorting" ,
			"d_dropdown" ,
			"d_dropdown@2x" ,
			"d_dropdown_toggle" ,
			"d_dropdown_toggle@2x" ,
			"d_EditCollider" ,
			"d_editcollision_16" ,
			"d_editcollision_16@2x" ,
			"d_editconstraints_16" ,
			"d_editconstraints_16@2x" ,
			"d_editicon.sml" ,
			"d_endButton" ,
			"d_endButton-On" ,
			"d_EventSystem Icon" ,
			"d_EventTrigger Icon" ,
			"d_Exposure@2x" ,
			"d_eyeDropper.Large" ,
			"d_eyeDropper.sml" ,
			"d_Favorite" ,
			"d_Favorite Icon" ,
			"d_Favorite@2x" ,
			"d_FilterByLabel" ,
			"d_FilterByLabel@2x" ,
			"d_FilterByType" ,
			"d_FilterByType@2x" ,
			"d_FilterSelectedOnly" ,
			"d_FilterSelectedOnly@2x" ,
			"d_Folder Icon" ,
			"d_FolderOpened Icon" ,
			"d_Font Icon" ,
			"d_forward" ,
			"d_forward@2x" ,
			"d_FrameCapture" ,
			"d_FrameCapture@2x" ,
			"d_FreeformLayoutGroup Icon" ,
			"d_GameObject Icon" ,
			"d_GEAR" ,
			"d_GraphicRaycaster Icon" ,
			"d_greenLight" ,
			"d_GridAndSnap@2x" ,
			"d_GridLayoutGroup Icon" ,
			"d_Groove" ,
			"d_HorizontalLayoutGroup Icon" ,
			"d_HorizontalSplit" ,
			"d_icon dropdown" ,
			"d_icon dropdown@2x" ,
			"d_ImageTargetBehaviour Icon" ,
			"d_IN_foldout" ,
			"d_IN_foldout@2x" ,
			"d_IN_foldout_act" ,
			"d_IN_foldout_act@2x" ,
			"d_IN_foldout_act_on" ,
			"d_IN_foldout_act_on@2x" ,
			"d_IN_foldout_on" ,
			"d_IN_foldout_on@2x" ,
			"d_InspectorLock" ,
			"d_JointAngularLimits" ,
			"d_Keyboard@2x" ,
			"d_KeyboardShortcutsDisabled@2x" ,
			"d_LayoutElement Icon" ,
			"d_leftBracket" ,
			"d_Lighting" ,
			"d_LightmapEditor.WindowTitle" ,
			"d_lightOff" ,
			"d_LightProbeProxyVolume Icon" ,
			"d_lightRim" ,
			"d_Linked" ,
			"d_Linked@2x" ,
			"d_LookAtConstraint Icon" ,
			"d_LookDevCenterLight" ,
			"d_LookDevCenterLight@2x" ,
			"d_LookDevClose" ,
			"d_LookDevClose@2x" ,
			"d_LookDevEnvRotation" ,
			"d_LookDevEnvRotation@2x" ,
			"d_LookDevMirrorViews" ,
			"d_LookDevMirrorViews@2x" ,
			"d_LookDevMirrorViewsActive" ,
			"d_LookDevMirrorViewsActive@2x" ,
			"d_LookDevMirrorViewsInactive" ,
			"d_LookDevMirrorViewsInactive@2x" ,
			"d_LookDevObjRotation" ,
			"d_LookDevObjRotation@2x" ,
			"d_LookDevPaneOption" ,
			"d_LookDevPaneOption@2x" ,
			"d_LookDevResetEnv" ,
			"d_LookDevResetEnv@2x" ,
			"d_LookDevShadow" ,
			"d_LookDevShadow@2x" ,
			"d_LookDevSideBySide" ,
			"d_LookDevSideBySide@2x" ,
			"d_LookDevSingle1" ,
			"d_LookDevSingle1@2x" ,
			"d_LookDevSingle2" ,
			"d_LookDevSingle2@2x" ,
			"d_LookDevSplit" ,
			"d_LookDevSplit@2x" ,
			"d_LookDevZone" ,
			"d_LookDevZone@2x" ,
			"d_Material Icon" ,
			"d_MidAirPositionerBehaviour Icon" ,
			"d_Mirror" ,
			"d_model large" ,
			"d_ModelTargetBehaviour Icon" ,
			"d_monologo" ,
			"d_more@2x" ,
			"d_MoreOptions" ,
			"d_MoreOptions@2x" ,
			"d_MoveTool" ,
			"d_MoveTool on" ,
			"d_MoveTool On@2x" ,
			"d_MoveTool@2x" ,
			"d_MultiTargetBehaviour Icon" ,
			"d_Navigation" ,
			"d_ObjectTargetBehaviour Icon" ,
			"d_Occlusion" ,
			"d_ol_minus" ,
			"d_ol_minus@2x" ,
			"d_ol_minus_act" ,
			"d_ol_minus_act@2x" ,
			"d_ol_plus" ,
			"d_ol_plus@2x" ,
			"d_ol_plus_act" ,
			"d_ol_plus_act@2x" ,
			"d_orangeLight" ,
			"d_OrientationGizmo@2x" ,
			"d_P4_AddedLocal" ,
			"d_P4_AddedRemote" ,
			"d_P4_CheckOutLocal" ,
			"d_P4_CheckOutRemote" ,
			"d_P4_Conflicted" ,
			"d_P4_DeletedLocal" ,
			"d_P4_DeletedRemote" ,
			"d_P4_Local" ,
			"d_P4_LockedLocal" ,
			"d_P4_LockedRemote" ,
			"d_P4_OutOfSync" ,
			"d_ParentConstraint Icon" ,
			"d_Particle Effect" ,
			"d_ParticleSystem Icon" ,
			"d_ParticleSystemForceField Icon" ,
			"d_PauseButton" ,
			"d_PauseButton On" ,
			"d_PauseButton On@2x" ,
			"d_PauseButton@2x" ,
			"d_PhysicalResolution Icon" ,
			"d_Physics2DRaycaster Icon" ,
			"d_PhysicsRaycaster Icon" ,
			"d_pick" ,
			"d_pick@2x" ,
			"d_PlaneFinderBehaviour Icon" ,
			"d_PlayableDirector Icon" ,
			"d_PlayButton" ,
			"d_PlayButton On" ,
			"d_PlayButton On@2x" ,
			"d_PlayButton@2x" ,
			"d_PlayButtonProfile" ,
			"d_PlayButtonProfile On" ,
			"d_playLoopOff" ,
			"d_playLoopOn" ,
			"d_PositionConstraint Icon" ,
			"d_preAudioAutoPlayOff" ,
			"d_preAudioAutoPlayOn" ,
			"d_preAudioLoopOff" ,
			"d_preAudioLoopOn" ,
			"d_preAudioPlayOff" ,
			"d_preAudioPlayOn" ,
			"d_Prefab Icon" ,
			"d_PrefabModel Icon" ,
			"d_PrefabOverlayAdded Icon" ,
			"d_PrefabOverlayRemoved Icon" ,
			"d_PrefabVariant Icon" ,
			"d_PreMatCube" ,
			"d_PreMatCylinder" ,
			"d_PreMatLight0" ,
			"d_PreMatLight1" ,
			"d_PreMatSphere" ,
			"d_PreMatTorus" ,
			"d_Preset.Context" ,
			"d_Preset.Context@2x" ,
			"d_PreTextureAlpha" ,
			"d_PreTextureMipMapHigh" ,
			"d_PreTextureMipMapLow" ,
			"d_PreTextureRGB" ,
			"d_Profiler.Audio" ,
			"d_Profiler.CPU" ,
			"d_Profiler.FirstFrame" ,
			"d_Profiler.GPU" ,
			"d_Profiler.LastFrame" ,
			"d_Profiler.Memory" ,
			"d_Profiler.Network" ,
			"d_Profiler.NextFrame" ,
			"d_Profiler.Physics" ,
			"d_Profiler.PrevFrame" ,
			"d_Profiler.Record" ,
			"d_Profiler.Rendering" ,
			"d_Profiler.Video" ,
			"d_ProfilerColumn.WarningCount" ,
			"d_ProfilerTimelineDigDownArrow" ,
			"d_ProfilerTimelineDigDownArrow@2x" ,
			"d_ProfilerTimelineRollUpArrow" ,
			"d_ProfilerTimelineRollUpArrow@2x" ,
			"d_Progress@2x" ,
			"d_Project" ,
			"d_Project@2x" ,
			"d_pulldown@2x" ,
			"d_RectTool" ,
			"d_RectTool On" ,
			"d_RectTool On@2x" ,
			"d_RectTool@2x" ,
			"d_RectTransform Icon" ,
			"d_RectTransformBlueprint" ,
			"d_RectTransformRaw" ,
			"d_redGroove" ,
			"d_redLight" ,
			"d_Refresh" ,
			"d_renderdoc" ,
			"d_rightBracket" ,
			"d_rol-body" ,
			"d_rol-header" ,
			"d_rol-tab" ,
			"d_RotateTool" ,
			"d_RotateTool On" ,
			"d_RotateTool On@2x" ,
			"d_RotateTool@2x" ,
			"d_RotationConstraint Icon" ,
			"d_ScaleConstraint Icon" ,
			"d_ScaleTool" ,
			"d_ScaleTool On" ,
			"d_ScaleTool On@2x" ,
			"d_ScaleTool@2x" ,
			"d_SceneAsset Icon" ,
			"d_scenepicking_notpickable@2x" ,
			"d_scenepicking_notpickable_hover@2x" ,
			"d_scenepicking_notpickable-mixed@2x" ,
			"d_scenepicking_notpickable-mixed_hover@2x" ,
			"d_scenepicking_pickable@2x" ,
			"d_scenepicking_pickable_hover@2x" ,
			"d_scenepicking_pickable-mixed@2x" ,
			"d_scenepicking_pickable-mixed_hover@2x" ,
			"d_SceneViewAlpha" ,
			"d_SceneViewAudio" ,
			"d_SceneViewAudio On@2x" ,
			"d_SceneViewAudio@2x" ,
			"d_SceneViewFx" ,
			"d_SceneViewLighting" ,
			"d_SceneViewOrtho" ,
			"d_SceneViewRGB" ,
			"d_SceneViewSnap" ,
			"d_SceneViewSnap@2x" ,
			"d_SceneViewVisibility@2x" ,
			"d_scenevis_hidden@2x" ,
			"d_scenevis_hidden_hover@2x" ,
			"d_scenevis_hidden-mixed@2x" ,
			"d_scenevis_hidden-mixed_hover@2x" ,
			"d_scenevis_visible@2x" ,
			"d_scenevis_visible_hover@2x" ,
			"d_scenevis_visible-mixed@2x" ,
			"d_scenevis_visible-mixed_hover@2x" ,
			"d_scrolldown" ,
			"d_scrolldown@2x" ,
			"d_scrolldown_uielements" ,
			"d_scrolldown_uielements@2x" ,
			"d_scrollleft" ,
			"d_scrollleft@2x" ,
			"d_scrollleft_uielements" ,
			"d_scrollleft_uielements@2x" ,
			"d_scrollright" ,
			"d_scrollright@2x" ,
			"d_scrollright_uielements" ,
			"d_scrollright_uielements@2x" ,
			"d_ScrollShadow" ,
			"d_scrollup" ,
			"d_scrollup@2x" ,
			"d_scrollup_uielements" ,
			"d_scrollup_uielements@2x" ,
			"d_ScrollViewArea Icon" ,
			"d_Search Icon" ,
			"d_search_icon" ,
			"d_search_icon@2x" ,
			"d_search_menu" ,
			"d_search_menu@2x" ,
			"d_SearchJump Icon" ,
			"d_SearchOverlay@2x" ,
			"d_SearchWindow@2x" ,
			"d_SelectionList Icon" ,
			"d_SelectionListItem Icon" ,
			"d_SelectionListTemplate Icon" ,
			"d_Settings" ,
			"d_Settings Icon" ,
			"d_SettingsIcon" ,
			"d_Shortcut Icon" ,
			"d_SnapIncrement" ,
			"d_SnapIncrement@2x" ,
			"d_SocialNetworks.FacebookShare" ,
			"d_SocialNetworks.LinkedInShare" ,
			"d_SocialNetworks.Tweet" ,
			"d_SocialNetworks.UDNOpen" ,
			"d_SortingGroup Icon" ,
			"d_SpeedScale" ,
			"d_StandaloneInputModule Icon" ,
			"d_StepButton" ,
			"d_StepButton On" ,
			"d_StepButton@2x" ,
			"d_StepLeftButton" ,
			"d_StepLeftButton-On" ,
			"d_StreamingController Icon" ,
			"d_StyleSheet Icon" ,
			"d_SVN_AddedLocal" ,
			"d_SVN_Conflicted" ,
			"d_SVN_DeletedLocal" ,
			"d_SVN_Local" ,
			"d_SVN_LockedLocal" ,
			"d_SVN_OutOfSync" ,
			"d_tab_next" ,
			"d_tab_next@2x" ,
			"d_tab_prev" ,
			"d_tab_prev@2x" ,
			"d_TerrainInspector.TerrainToolLower On" ,
			"d_TerrainInspector.TerrainToolLowerAlt" ,
			"d_TerrainInspector.TerrainToolPlants" ,
			"d_TerrainInspector.TerrainToolPlants On" ,
			"d_TerrainInspector.TerrainToolPlantsAlt" ,
			"d_TerrainInspector.TerrainToolPlantsAlt On" ,
			"d_TerrainInspector.TerrainToolRaise" ,
			"d_TerrainInspector.TerrainToolRaise On" ,
			"d_TerrainInspector.TerrainToolSetheight" ,
			"d_TerrainInspector.TerrainToolSetheight On" ,
			"d_TerrainInspector.TerrainToolSetheightAlt" ,
			"d_TerrainInspector.TerrainToolSetheightAlt On" ,
			"d_TerrainInspector.TerrainToolSettings" ,
			"d_TerrainInspector.TerrainToolSettings On" ,
			"d_TerrainInspector.TerrainToolSmoothHeight" ,
			"d_TerrainInspector.TerrainToolSmoothHeight On" ,
			"d_TerrainInspector.TerrainToolSplat" ,
			"d_TerrainInspector.TerrainToolSplat On" ,
			"d_TerrainInspector.TerrainToolSplatAlt" ,
			"d_TerrainInspector.TerrainToolSplatAlt On" ,
			"d_TerrainInspector.TerrainToolTrees" ,
			"d_TerrainInspector.TerrainToolTrees On" ,
			"d_TerrainInspector.TerrainToolTreesAlt" ,
			"d_TerrainInspector.TerrainToolTreesAlt On" ,
			"d_TextAsset Icon" ,
			"d_Texture2D Icon" ,
			"d_ThemeStyleSheet Icon" ,
			"d_TimelineAsset Icon" ,
			"d_TimelineDigIn" ,
			"d_TimelineEditModeMixOFF" ,
			"d_TimelineEditModeMixON" ,
			"d_TimelineEditModeReplaceOFF" ,
			"d_TimelineEditModeReplaceON" ,
			"d_TimelineEditModeRippleOFF" ,
			"d_TimelineEditModeRippleON" ,
			"d_TimelineSelector" ,
			"d_toggle_bg" ,
			"d_toggle_bg@2x" ,
			"d_toggle_bg_focus" ,
			"d_toggle_bg_focus@2x" ,
			"d_toggle_bg_hover" ,
			"d_toggle_bg_hover@2x" ,
			"d_toggle_mixed_bg" ,
			"d_toggle_mixed_bg@2x" ,
			"d_toggle_mixed_bg_focus" ,
			"d_toggle_mixed_bg_focus@2x" ,
			"d_toggle_mixed_bg_hover" ,
			"d_toggle_mixed_bg_hover@2x" ,
			"d_toggle_on" ,
			"d_toggle_on@2x" ,
			"d_toggle_on_focus" ,
			"d_toggle_on_focus@2x" ,
			"d_toggle_on_hover" ,
			"d_toggle_on_hover@2x" ,
			"d_Toolbar Minus" ,
			"d_Toolbar Plus" ,
			"d_Toolbar Plus More" ,
			"d_ToolHandleCenter" ,
			"d_ToolHandleCenter@2x" ,
			"d_ToolHandleGlobal" ,
			"d_ToolHandleGlobal@2x" ,
			"d_ToolHandleLocal" ,
			"d_ToolHandleLocal@2x" ,
			"d_ToolHandlePivot" ,
			"d_ToolHandlePivot@2x" ,
			"d_ToolSettings@2x" ,
			"d_TouchInputModule Icon" ,
			"d_tranp" ,
			"d_TransformTool" ,
			"d_TransformTool On" ,
			"d_TransformTool On@2x" ,
			"d_TransformTool@2x" ,
			"d_tree_icon" ,
			"d_tree_icon_branch" ,
			"d_tree_icon_branch_frond" ,
			"d_tree_icon_frond" ,
			"d_tree_icon_leaf" ,
			"d_TreeEditor.AddBranches" ,
			"d_TreeEditor.AddLeaves" ,
			"d_TreeEditor.Branch" ,
			"d_TreeEditor.Branch On" ,
			"d_TreeEditor.BranchFreeHand" ,
			"d_TreeEditor.BranchFreeHand On" ,
			"d_TreeEditor.BranchRotate" ,
			"d_TreeEditor.BranchRotate On" ,
			"d_TreeEditor.BranchScale" ,
			"d_TreeEditor.BranchScale On" ,
			"d_TreeEditor.BranchTranslate" ,
			"d_TreeEditor.BranchTranslate On" ,
			"d_TreeEditor.Distribution" ,
			"d_TreeEditor.Distribution On" ,
			"d_TreeEditor.Duplicate" ,
			"d_TreeEditor.Geometry" ,
			"d_TreeEditor.Geometry On" ,
			"d_TreeEditor.Leaf" ,
			"d_TreeEditor.Leaf On" ,
			"d_TreeEditor.LeafFreeHand" ,
			"d_TreeEditor.LeafFreeHand On" ,
			"d_TreeEditor.LeafRotate" ,
			"d_TreeEditor.LeafRotate On" ,
			"d_TreeEditor.LeafScale" ,
			"d_TreeEditor.LeafScale On" ,
			"d_TreeEditor.LeafTranslate" ,
			"d_TreeEditor.LeafTranslate On" ,
			"d_TreeEditor.Material" ,
			"d_TreeEditor.Material On" ,
			"d_TreeEditor.Refresh" ,
			"d_TreeEditor.Trash" ,
			"d_TreeEditor.Wind" ,
			"d_TreeEditor.Wind On" ,
			"d_UndoHistory" ,
			"d_UndoHistory@2x" ,
			"d_UnityEditor.AnimationWindow" ,
			"d_UnityEditor.ConsoleWindow" ,
			"d_UnityEditor.ConsoleWindow@2x" ,
			"d_UnityEditor.DebugInspectorWindow" ,
			"d_UnityEditor.FindDependencies" ,
			"d_UnityEditor.GameView" ,
			"d_UnityEditor.GameView@2x" ,
			"d_UnityEditor.HierarchyWindow" ,
			"d_UnityEditor.InspectorWindow" ,
			"d_UnityEditor.InspectorWindow@2x" ,
			"d_UnityEditor.LookDevView" ,
			"d_UnityEditor.ProfilerWindow" ,
			"d_UnityEditor.SceneHierarchyWindow" ,
			"d_UnityEditor.SceneHierarchyWindow@2x" ,
			"d_UnityEditor.SceneView" ,
			"d_UnityEditor.SceneView@2x" ,
			"d_UnityEditor.Timeline.TimelineWindow" ,
			"d_UnityEditor.VersionControl" ,
			"d_UnityLogo" ,
			"d_Unlinked" ,
			"d_Unlinked@2x" ,
			"d_UserDefinedTargetBuildingBehaviour Icon" ,
			"d_VerticalLayoutGroup Icon" ,
			"d_VerticalSplit" ,
			"d_ViewOptions@2x" ,
			"d_ViewToolMove" ,
			"d_ViewToolMove On" ,
			"d_ViewToolMove On@2x" ,
			"d_ViewToolMove@2x" ,
			"d_ViewToolOrbit" ,
			"d_ViewToolOrbit On" ,
			"d_ViewToolOrbit On@2x" ,
			"d_ViewToolOrbit@2x" ,
			"d_ViewToolZoom" ,
			"d_ViewToolZoom On" ,
			"d_ViewToolZoom On@2x" ,
			"d_ViewToolZoom@2x" ,
			"d_VirtualButtonBehaviour Icon" ,
			"d_VisibilityOff" ,
			"d_VisibilityOn" ,
			"d_VisualEffect Icon" ,
			"d_VisualEffectAsset Icon" ,
			"d_VisualTreeAsset Icon" ,
			"d_VuforiaBehaviour Icon" ,
			"d_VuMarkBehaviour Icon" ,
			"d_VUMeterTextureHorizontal" ,
			"d_VUMeterTextureVertical" ,
			"d_WaitSpin00" ,
			"d_WaitSpin01" ,
			"d_WaitSpin02" ,
			"d_WaitSpin03" ,
			"d_WaitSpin04" ,
			"d_WaitSpin05" ,
			"d_WaitSpin06" ,
			"d_WaitSpin07" ,
			"d_WaitSpin08" ,
			"d_WaitSpin09" ,
			"d_WaitSpin10" ,
			"d_WaitSpin11" ,
			"d_WelcomeScreen.AssetStoreLogo" ,
			"d_winbtn_graph" ,
			"d_winbtn_graph_close_h" ,
			"d_winbtn_graph_max_h" ,
			"d_winbtn_graph_min_h" ,
			"d_winbtn_mac_close" ,
			"d_winbtn_mac_close_a" ,
			"d_winbtn_mac_close_h" ,
			"d_winbtn_mac_close_h@2x" ,
			"d_winbtn_mac_inact" ,
			"d_winbtn_mac_max" ,
			"d_winbtn_mac_max_a" ,
			"d_winbtn_mac_max_h" ,
			"d_winbtn_mac_min" ,
			"d_winbtn_mac_min_a" ,
			"d_winbtn_mac_min_h" ,
			"d_winbtn_win_close" ,
			"d_winbtn_win_close@2x" ,
			"d_winbtn_win_close_a" ,
			"d_winbtn_win_close_a@2x" ,
			"d_winbtn_win_close_h" ,
			"d_winbtn_win_close_h@2x" ,
			"d_winbtn_win_max" ,
			"d_winbtn_win_max@2x" ,
			"d_winbtn_win_max_a" ,
			"d_winbtn_win_max_a@2x" ,
			"d_winbtn_win_max_h" ,
			"d_winbtn_win_max_h@2x" ,
			"d_winbtn_win_min" ,
			"d_winbtn_win_min_a" ,
			"d_winbtn_win_min_h" ,
			"d_winbtn_win_rest" ,
			"d_winbtn_win_rest_a" ,
			"d_winbtn_win_rest_h" ,
			"d_winbtn_win_restore" ,
			"d_winbtn_win_restore@2x" ,
			"d_winbtn_win_restore_a" ,
			"d_winbtn_win_restore_a@2x" ,
			"d_winbtn_win_restore_h" ,
			"d_winbtn_win_restore_h@2x" ,
			"d_WireframeBehaviour Icon" ,
			"darkviewbackground" ,
			"darkviewbackground@2x" ,
			"Debug_Frame_d@2x" ,
			"DefaultAsset Icon" ,
			"DefaultShaderInfoTexFloat" ,
			"DefaultSlate Icon" ,
			"DefaultSorting" ,
			"DirectionalLight Gizmo" ,
			"DirectionalLight Icon" ,
			"DiscLight Gizmo" ,
			"DiscLight Icon" ,
			"DistanceJoint2D Icon" ,
			"dll Script Icon" ,
			"dockarea back" ,
			"dockarea back@2x" ,
			"dockarea overlay" ,
			"dockarea overlay@2x" ,
			"DotFill" ,
			"DotFrame" ,
			"DotFrameDotted" ,
			"DotSelection" ,
			"Dropdown Icon" ,
			"dropdown_PreviewPackages" ,
			"dropdown_PreviewPackages@2x" ,
			"dropwell nothumb" ,
			"dropwell nothumb focus" ,
			"dropwell nothumb focus@2x" ,
			"dropwell nothumb@2x" ,
			"dropwell predrop" ,
			"dropwell predrop@2x" ,
			"EchoFilter Icon" ,
			"EdgeCollider2D Icon" ,
			"EditCollider" ,
			"editcollision_16" ,
			"editconstraints_16" ,
			"editicon.sml" ,
			"EditorSettings Icon" ,
			"endButton" ,
			"endButton-On" ,
			"EventSystem Icon" ,
			"EventTrigger Icon" ,
			"ExposablePopupBg" ,
			"eyeDropper.Large" ,
			"EyeDropper.Large" ,
			"eyeDropper.sml" ,
			"Favorite" ,
			"Favorite Icon" ,
			"FilterByLabel" ,
			"FilterByType" ,
			"FilterSelectedOnly" ,
			"FilterSelectedOnly@2x" ,
			"FixedJoint Icon" ,
			"FixedJoint2D Icon" ,
			"Flare Icon" ,
			"FlareLayer Icon" ,
			"Folder Icon" ,
			"FolderEmpty Icon" ,
			"FolderFavorite Icon" ,
			"Font Icon" ,
			"Font Texture" ,
			"forward" ,
			"forward@2x" ,
			"FreeformLayoutGroup Icon" ,
			"FrictionJoint2D Icon" ,
			"GameManager Icon" ,
			"GameObject Icon" ,
			"gameviewbackground" ,
			"gameviewbackground@2x" ,
			"GEAR" ,
			"GizmoIconAtlas_pix32" ,
			"GraphicRaycaster Icon" ,
			"greenLight" ,
			"grey_border" ,
			"grey_border@2x" ,
			"Grid Icon" ,
			"Grid.BoxTool" ,
			"Grid.Default" ,
			"Grid.EraserTool" ,
			"Grid.FillTool" ,
			"Grid.MoveTool" ,
			"Grid.PaintTool" ,
			"Grid.PickingTool" ,
			"Grid.SelectTool" ,
			"GridBrush Icon" ,
			"GridLayoutGroup Icon" ,
			"Groove" ,
			"GUILayer Icon" ,
			"GUISkin Icon" ,
			"GUIText Icon" ,
			"GUITexture Icon" ,
			"gulim Atlas" ,
			"Halo Icon" ,
			"Head" ,
			"HeadIk" ,
			"HeadZoom" ,
			"HeadZoomSilhouette" ,
			"helpbox" ,
			"helpbox@2x" ,
			"Helvetica Atlas" ,
			"HighPassFilter Icon" ,
			"HingeJoint Icon" ,
			"HingeJoint2D Icon" ,
			"HoloLensInputModule Icon" ,
			"HorizontalLayoutGroup Icon" ,
			"HorizontalSplit" ,
			"HumanTemplate Icon" ,
			"icon dropdown" ,
			"Icon Dropdown" ,
			"iconselector sep" ,
			"iconselector sep@2x" ,
			"Image Icon" ,
			"ImageTargetBehaviour Icon" ,
			"IN BigTitle" ,
			"IN BigTitle Post" ,
			"IN BigTitle Post@2x" ,
			"IN BigTitle@2x" ,
			"IN foldout" ,
			"IN foldout act on" ,
			"IN foldout act on@2x" ,
			"IN foldout act@2x" ,
			"IN foldout focus" ,
			"IN foldout focus on" ,
			"IN foldout focus on@2x" ,
			"IN foldout focus@2x" ,
			"IN foldout on" ,
			"IN foldout on@2x" ,
			"IN foldout@2x" ,
			"IN LockButton" ,
			"IN LockButton act@2x" ,
			"IN LockButton on" ,
			"IN LockButton on act" ,
			"IN LockButton on act@2x" ,
			"IN LockButton on@2x" ,
			"IN LockButton@2x" ,
			"IN pulldown" ,
			"IN pulldown@2x" ,
			"IN Title Active" ,
			"IN Title Focused" ,
			"IN Title Normal" ,
			"IN Title On Active" ,
			"IN Title On Focused" ,
			"IN Title On Normal" ,
			"Inlined TextField Focus" ,
			"Inlined TextField Focus@2x" ,
			"InputField Icon" ,
			"InspectorLock" ,
			"Inter-Italic Atlas" ,
			"Inter-Regular Atlas" ,
			"Inter-SemiBold Atlas" ,
			"Inter-SemiBoldItalic Atlas" ,
			"JointAngularLimits" ,
			"js Script Icon" ,
			"KnobCShape" ,
			"KnobCShapeMini" ,
			"LayoutElement Icon" ,
			"LeftArm" ,
			"leftBracket" ,
			"LeftFeetIk" ,
			"LeftFingers" ,
			"LeftFingersIk" ,
			"LeftHandZoom" ,
			"LeftHandZoomSilhouette" ,
			"LeftLeg" ,
			"LensFlare Gizmo" ,
			"LensFlare Icon" ,
			"Light Icon" ,
			"Lighting" ,
			"LightingDataAsset Icon" ,
			"LightingDataAssetParent Icon" ,
			"LightmapEditor.WindowTitle" ,
			"LightmapParameters Icon" ,
			"Lightmapping" ,
			"lightMeter/greenLight" ,
			"lightMeter/lightRim" ,
			"lightMeter/orangeLight" ,
			"lightMeter/redLight" ,
			"lightOff" ,
			"LightProbeGroup Gizmo" ,
			"LightProbeGroup Icon" ,
			"LightProbeProxyVolume Gizmo" ,
			"LightProbeProxyVolume Icon" ,
			"LightProbes Icon" ,
			"lightRim" ,
			"LineRenderer Icon" ,
			"LockIcon" ,
			"LockIcon-On" ,
			"LODGroup Icon" ,
			"LookAtConstraint Icon" ,
			"LookDevCenterLight" ,
			"LookDevCenterLightl@2x" ,
			"LookDevClose" ,
			"LookDevClose@2x" ,
			"LookDevEnvRotation" ,
			"LookDevEnvRotation@2x" ,
			"LookDevEyedrop" ,
			"LookDevLight" ,
			"LookDevLight@2x" ,
			"LookDevMirrorViewsActive" ,
			"LookDevMirrorViewsActive@2x" ,
			"LookDevMirrorViewsInactive" ,
			"LookDevMirrorViewsInactive@2x" ,
			"LookDevObjRotation" ,
			"LookDevObjRotation@2x" ,
			"LookDevPaneOption" ,
			"LookDevPaneOption@2x" ,
			"LookDevResetEnv" ,
			"LookDevResetEnv@2x" ,
			"LookDevShadow" ,
			"LookDevShadow@2x" ,
			"LookDevShadowFrame" ,
			"LookDevShadowFrame@2x" ,
			"LookDevSideBySide" ,
			"LookDevSideBySide@2x" ,
			"LookDevSingle1" ,
			"LookDevSingle1@2x" ,
			"LookDevSingle2" ,
			"LookDevSingle2@2x" ,
			"LookDevSplit" ,
			"LookDevSplit@2x" ,
			"LookDevZone" ,
			"LookDevZone@2x" ,
			"loop" ,
			"LowPassFilter Icon" ,
			"Main Light Gizmo" ,
			"MALGUN Atlas" ,
			"MALGUNBD Atlas" ,
			"Mask Icon" ,
			"MaskEditor_Root" ,
			"Material Icon" ,
			"Mesh Icon" ,
			"MeshCollider Icon" ,
			"MeshFilter Icon" ,
			"MeshRenderer Icon" ,
			"MetaFile Icon" ,
			"Microphone Icon" ,
			"Microsoft Sans Serif Atlas" ,
			"MidAirPositionerBehaviour Icon" ,
			"mini btn" ,
			"mini btn act" ,
			"mini btn act@2x" ,
			"mini btn focus" ,
			"mini btn focus@2x" ,
			"mini btn left" ,
			"mini btn left act" ,
			"mini btn left act@2x" ,
			"mini btn left focus" ,
			"mini btn left focus@2x" ,
			"mini btn left on" ,
			"mini btn left on focus" ,
			"mini btn left on focus@2x" ,
			"mini btn left on@2x" ,
			"mini btn left onact" ,
			"mini btn left onact@2x" ,
			"mini btn left@2x" ,
			"mini btn mid" ,
			"mini btn mid act" ,
			"mini btn mid act@2x" ,
			"mini btn mid focus" ,
			"mini btn mid focus@2x" ,
			"mini btn mid on" ,
			"mini btn mid on focus" ,
			"mini btn mid on focus@2x" ,
			"mini btn mid on@2x" ,
			"mini btn mid onact" ,
			"mini btn mid onact@2x" ,
			"mini btn mid@2x" ,
			"mini btn on" ,
			"mini btn on focus" ,
			"mini btn on focus@2x" ,
			"mini btn on@2x" ,
			"mini btn onact" ,
			"mini btn onact@2x" ,
			"mini btn right" ,
			"mini btn right act" ,
			"mini btn right act@2x" ,
			"mini btn right focus" ,
			"mini btn right focus@2x" ,
			"mini btn right on" ,
			"mini btn right on focus" ,
			"mini btn right on focus@2x" ,
			"mini btn right on@2x" ,
			"mini btn right onact" ,
			"mini btn right onact@2x" ,
			"mini btn right@2x" ,
			"mini btn@2x" ,
			"mini popup act" ,
			"mini popup act@2x" ,
			"mini popup focus" ,
			"mini popup focus@2x" ,
			"mini popup@2x" ,
			"mini pulldown act" ,
			"mini pulldown act@2x" ,
			"mini pulldown focus" ,
			"mini pulldown focus@2x" ,
			"mini pulldown@2x" ,
			"miniscrollerhorizontal" ,
			"Mirror" ,
			"ModelTargetBehaviour Icon" ,
			"monologo" ,
			"MonoLogo" ,
			"Motion Icon" ,
			"MoveTool" ,
			"MoveTool on" ,
			"MoveTool On" ,
			"MovieTexture Icon" ,
			"MS Gothic Atlas" ,
			"MSJH Atlas" ,
			"MSJHBD Atlas" ,
			"msyh_0 Atlas" ,
			"MultiTargetBehaviour Icon" ,
			"MuscleClip Icon" ,
			"Navigation" ,
			"NavMeshAgent Icon" ,
			"NavMeshData Icon" ,
			"NavMeshObstacle Icon" ,
			"NetworkAnimator Icon" ,
			"NetworkDiscovery Icon" ,
			"NetworkIdentity Icon" ,
			"NetworkLobbyManager Icon" ,
			"NetworkLobbyPlayer Icon" ,
			"NetworkManager Icon" ,
			"NetworkManagerHUD Icon" ,
			"NetworkMigrationManager Icon" ,
			"NetworkProximityChecker Icon" ,
			"NetworkStartPosition Icon" ,
			"NetworkTransform Icon" ,
			"NetworkTransformChild Icon" ,
			"NetworkTransformVisualizer Icon" ,
			"NetworkView Icon" ,
			"NIRMALA Atlas" ,
			"ObjectPickerTab" ,
			"ObjectPickerTab@2x" ,
			"ObjectTargetBehaviour Icon" ,
			"Occlusion" ,
			"OcclusionArea Icon" ,
			"OcclusionPortal Icon" ,
			"OffMeshLink Icon" ,
			"OL box" ,
			"OL box on" ,
			"OL box on@2x" ,
			"OL box@2x" ,
			"OL Highlight" ,
			"OL Highlight@2x" ,
			"ol minus act" ,
			"ol minus act@2x" ,
			"ol plus act" ,
			"ol plus act@2x" ,
			"orangeLight" ,
			"Outline Icon" ,
			"P4_AddedLocal" ,
			"P4_AddedRemote" ,
			"P4_BlueLeftParenthesis" ,
			"P4_BlueRightParenthesis" ,
			"P4_CheckOutLocal" ,
			"P4_CheckOutRemote" ,
			"P4_Conflicted" ,
			"P4_DeletedLocal" ,
			"P4_DeletedRemote" ,
			"P4_Local" ,
			"P4_LockedLocal" ,
			"P4_LockedRemote" ,
			"P4_OutOfSync" ,
			"P4_RedLeftParenthesis" ,
			"P4_RedRightParenthesis" ,
			"P4_Updating" ,
			"package_installed" ,
			"package_update" ,
			"PackageBadgeDelete" ,
			"PackageBadgeNew" ,
			"pane options" ,
			"pane options@2x" ,
			"ParentConstraint Icon" ,
			"Particle Effect" ,
			"ParticleSystem Gizmo" ,
			"ParticleSystem Icon" ,
			"ParticleSystemForceField Gizmo" ,
			"ParticleSystemForceField Icon" ,
			"PauseButton" ,
			"PauseButton Anim" ,
			"PauseButton On" ,
			"PB-BottomBarBg" ,
			"PB-HeaderBgMiddle" ,
			"PB-HeaderBgTop" ,
			"PB-TopBarBg" ,
			"PhysicMaterial Icon" ,
			"Physics2DRaycaster Icon" ,
			"PhysicsMaterial2D Icon" ,
			"PhysicsRaycaster Icon" ,
			"PingFang Atlas" ,
			"PlaneFinderBehaviour Icon" ,
			"PlatformEffector2D Icon" ,
			"PlayableDirector Icon" ,
			"PlayButton" ,
			"PlayButton Anim" ,
			"PlayButton On" ,
			"PlayButtonProfile" ,
			"PlayButtonProfile Anim" ,
			"PlayButtonProfile On" ,
			"playLoopOff" ,
			"playLoopOn" ,
			"playSpeed" ,
			"PointEffector2D Icon" ,
			"PointLight Gizmo" ,
			"PolygonCollider2D Icon" ,
			"PositionAsUV1 Icon" ,
			"PositionConstraint Icon" ,
			"PR DropHere" ,
			"PR DropHere@2x" ,
			"Pre button" ,
			"Pre button act" ,
			"Pre button act@2x" ,
			"Pre button on" ,
			"Pre button on@2x" ,
			"Pre button@2x" ,
			"Pre popup act" ,
			"Pre popup on" ,
			"Pre toolbar" ,
			"Pre toolbar a" ,
			"Pre toolbar a@2x" ,
			"Pre toolbar act overlay" ,
			"Pre toolbar act overlay@2x" ,
			"Pre toolbar@2x" ,
			"preAudioAutoPlayOff" ,
			"preAudioAutoPlayOn" ,
			"preAudioLoopOff" ,
			"preAudioLoopOn" ,
			"preAudioPlayOff" ,
			"preAudioPlayOn" ,
			"Prefab Icon" ,
			"PrefabModel Icon" ,
			"PrefabNormal Icon" ,
			"PrefabOverlayAdded Icon" ,
			"PrefabOverlayModified Icon" ,
			"PrefabOverlayRemoved Icon" ,
			"PrefabVariant Icon" ,
			"PreMatCube" ,
			"PreMatCylinder" ,
			"PreMatLight0" ,
			"PreMatLight1" ,
			"PreMatQuad" ,
			"PreMatSphere" ,
			"PreMatTorus" ,
			"Preset Icon" ,
			"Preset.Context" ,
			"PreTextureAlpha" ,
			"PreTextureArrayFirstSlice" ,
			"PreTextureArrayLastSlice" ,
			"PreTextureMipMapHigh" ,
			"PreTextureMipMapLow" ,
			"PreTextureRGB" ,
			"PreviewPackageInUse" ,
			"PreviewPackageInUse@2x" ,
			"ProceduralMaterial Icon" ,
			"Profiler.Audio" ,
			"Profiler.CPU" ,
			"Profiler.FirstFrame" ,
			"Profiler.GlobalIllumination" ,
			"Profiler.GPU" ,
			"Profiler.Instrumentation" ,
			"Profiler.LastFrame" ,
			"Profiler.Memory" ,
			"Profiler.NetworkMessages" ,
			"Profiler.NetworkOperations" ,
			"Profiler.NextFrame" ,
			"Profiler.Physics" ,
			"Profiler.Physics2D" ,
			"Profiler.PrevFrame" ,
			"Profiler.Record" ,
			"Profiler.Rendering" ,
			"Profiler.UI" ,
			"Profiler.UIDetails" ,
			"Profiler.Video" ,
			"ProfilerBadge" ,
			"ProfilerBadge@2x" ,
			"ProfilerColumn.WarningCount" ,
			"ProfilerLeftPane" ,
			"ProfilerLeftPane@2x" ,
			"ProfilerNoDataAvailableOverlayDark" ,
			"ProfilerNoDataAvailableOverlayDarkOn" ,
			"ProfilerRightPaneBackground" ,
			"ProfilerRightPaneBackground@2x" ,
			"ProfilerRightPaneBackgroundOn" ,
			"ProfilerRightPaneBackgroundOn@2x" ,
			"progress back" ,
			"progress back@2x" ,
			"progress front" ,
			"progress front@2x" ,
			"ProilerLeftPaneOn" ,
			"ProilerLeftPaneOn@2x" ,
			"Project" ,
			"ProjectBrowserGridLabel" ,
			"ProjectBrowserGridLabelUnfocused" ,
			"ProjectBrowserIconAreaBg" ,
			"Projector Gizmo" ,
			"Projector Icon" ,
			"pulldown act" ,
			"pulldown act@2x" ,
			"pulldown focus" ,
			"pulldown focus@2x" ,
			"pulldown@2x" ,
			"RawImage Icon" ,
			"RaycastCollider Icon" ,
			"RectMask2D Icon" ,
			"RectTool" ,
			"RectTool On" ,
			"RectTransform Icon" ,
			"RectTransformBlueprint" ,
			"RectTransformRaw" ,
			"redGroove" ,
			"redLight" ,
			"ReflectionProbe Gizmo" ,
			"ReflectionProbe Icon" ,
			"Refresh" ,
			"RelativeJoint2D Icon" ,
			"renderdoc" ,
			"RenderTexture Icon" ,
			"RepaintDot@2x" ,
			"ReverbFilter Icon" ,
			"RightArm" ,
			"rightBracket" ,
			"RightFeetIk" ,
			"RightFingers" ,
			"RightFingersIk" ,
			"RightHandZoom" ,
			"RightHandZoomSilhouette" ,
			"RightLeg" ,
			"Rigidbody Icon" ,
			"Rigidbody2D Icon" ,
			"ro_selected_d" ,
			"ro_unselected_d" ,
			"RotateTool" ,
			"RotateTool On" ,
			"RotationConstraint Icon" ,
			"SaveActive" ,
			"SaveFromPlay" ,
			"SavePassive" ,
			"ScaleConstraint Icon" ,
			"ScaleTool" ,
			"ScaleTool On" ,
			"SceneAsset Icon" ,
			"SceneLoadIn" ,
			"SceneLoadOut" ,
			"SceneSave" ,
			"SceneSaveGrey" ,
			"SceneSet Icon" ,
			"SceneViewAlpha" ,
			"SceneviewAudio" ,
			"SceneViewAudio" ,
			"SceneViewFx" ,
			"SceneviewLighting" ,
			"SceneViewLighting" ,
			"SceneViewOrtho" ,
			"SceneViewRGB" ,
			"ScriptableObject Icon" ,
			"scroll horiz" ,
			"scroll horiz left act" ,
			"scroll horiz left act@2x" ,
			"scroll horiz left@2x" ,
			"scroll horiz right act" ,
			"scroll horiz right act@2x" ,
			"scroll horiz right@2x" ,
			"scroll horiz thumb" ,
			"scroll horiz thumb@2x" ,
			"scroll horiz@2x" ,
			"scroll vert" ,
			"scroll vert down act" ,
			"scroll vert down act@2x" ,
			"scroll vert down@2x" ,
			"scroll vert thumb" ,
			"scroll vert thumb@2x" ,
			"scroll vert up act" ,
			"scroll vert up act@2x" ,
			"scroll vert up@2x" ,
			"scroll vert@2x" ,
			"Scrollbar Icon" ,
			"ScrollRect Icon" ,
			"ScrollShadow" ,
			"scrubber background" ,
			"scrubber button" ,
			"scrubber button act" ,
			"search focused" ,
			"search focused@2x" ,
			"Search Icon" ,
			"search@2x" ,
			"searchCancelButton@2x" ,
			"searchCancelButtonActive" ,
			"searchCancelButtonActive@2x" ,
			"searchCancelButtonOff" ,
			"searchCancelButtonOff@2x" ,
			"SearchModeFilter" ,
			"Selectable Icon" ,
			"selected" ,
			"selected@2x" ,
			"Settings" ,
			"SettingsIcon" ,
			"Shader Icon" ,
			"ShaderVariantCollection Icon" ,
			"Shadow Icon" ,
			"ShurikenDropdownFocused" ,
			"ShurikenObjectField" ,
			"ShurikenObjectFieldFocused" ,
			"ShurikenObjectFieldPreDrop" ,
			"ShurikenPopupFocused" ,
			"ShurikenTextField" ,
			"ShurikenTextFieldFocused" ,
			"ShurikenToggleFocused" ,
			"ShurikenToggleFocused@2x" ,
			"ShurikenToggleFocusedOn" ,
			"ShurikenToggleFocusedOn@2x" ,
			"ShurikenToggleHover" ,
			"ShurikenToggleHover@2x" ,
			"ShurikenToggleHoverOn" ,
			"ShurikenToggleHoverOn@2x" ,
			"ShurikenToggleMixed" ,
			"ShurikenToggleMixed@2x" ,
			"ShurikenToggleNormal" ,
			"ShurikenToggleNormal@2x" ,
			"ShurikenToggleNormalMixed" ,
			"ShurikenToggleNormalMixed@2x" ,
			"ShurikenToggleNormalOn" ,
			"ShurikenToggleNormalOn@2x" ,
			"SkinnedMeshRenderer Icon" ,
			"Skybox Icon" ,
			"slider horiz" ,
			"slider horiz@2x" ,
			"Slider Icon" ,
			"slider thumb" ,
			"slider thumb act" ,
			"slider thumb act@2x" ,
			"slider thumb focus" ,
			"slider thumb focus@2x" ,
			"slider thumb@2x" ,
			"slider vert" ,
			"slider vert@2x" ,
			"SliderJoint2D Icon" ,
			"SocialNetworks.FacebookShare" ,
			"SocialNetworks.LinkedInShare" ,
			"SocialNetworks.Tweet" ,
			"SocialNetworks.UDNLogo" ,
			"SocialNetworks.UDNOpen" ,
			"Soft" ,
			"SoftlockInline" ,
			"SoftlockProjectBrowser Icon" ,
			"SortingGroup Icon" ,
			"SpatialMappingCollider Icon" ,
			"SpatialMappingRenderer Icon" ,
			"SpeedScale" ,
			"SpeedTreeModel Icon" ,
			"SphereCollider Icon" ,
			"SpotLight Gizmo" ,
			"Spotlight Icon" ,
			"SpringJoint Icon" ,
			"SpringJoint2D Icon" ,
			"Sprite Icon" ,
			"SpriteAtlas Icon" ,
			"SpriteCollider Icon" ,
			"SpriteMask Icon" ,
			"SpriteRenderer Icon" ,
			"SpriteShapeRenderer Icon" ,
			"StandaloneInputModule Icon" ,
			"StateMachineEditor.ArrowTip" ,
			"StateMachineEditor.ArrowTipSelected" ,
			"StateMachineEditor.Background" ,
			"StateMachineEditor.State" ,
			"StateMachineEditor.StateHover" ,
			"StateMachineEditor.StateSelected" ,
			"StateMachineEditor.StateSub" ,
			"StateMachineEditor.StateSubHover" ,
			"StateMachineEditor.StateSubSelected" ,
			"StateMachineEditor.UpButton" ,
			"StateMachineEditor.UpButtonHover" ,
			"StepButton" ,
			"StepButton Anim" ,
			"StepButton On" ,
			"StepLeftButton" ,
			"StepLeftButton-On" ,
			"sticky_arrow" ,
			"sticky_p4" ,
			"sticky_skin" ,
			"StreamingController Icon" ,
			"StyleSheet Icon" ,
			"SubstanceArchive Icon" ,
			"SurfaceEffector2D Icon" ,
			"sv_icon_dot0_pix16_gizmo" ,
			"sv_icon_dot0_sml" ,
			"sv_icon_dot1_pix16_gizmo" ,
			"sv_icon_dot1_sml" ,
			"sv_icon_dot10_pix16_gizmo" ,
			"sv_icon_dot10_sml" ,
			"sv_icon_dot11_pix16_gizmo" ,
			"sv_icon_dot11_sml" ,
			"sv_icon_dot12_pix16_gizmo" ,
			"sv_icon_dot12_sml" ,
			"sv_icon_dot13_pix16_gizmo" ,
			"sv_icon_dot13_sml" ,
			"sv_icon_dot14_pix16_gizmo" ,
			"sv_icon_dot14_sml" ,
			"sv_icon_dot15_pix16_gizmo" ,
			"sv_icon_dot15_sml" ,
			"sv_icon_dot2_pix16_gizmo" ,
			"sv_icon_dot2_sml" ,
			"sv_icon_dot3_pix16_gizmo" ,
			"sv_icon_dot3_sml" ,
			"sv_icon_dot4_pix16_gizmo" ,
			"sv_icon_dot4_sml" ,
			"sv_icon_dot5_pix16_gizmo" ,
			"sv_icon_dot5_sml" ,
			"sv_icon_dot6_pix16_gizmo" ,
			"sv_icon_dot6_sml" ,
			"sv_icon_dot7_pix16_gizmo" ,
			"sv_icon_dot7_sml" ,
			"sv_icon_dot8_pix16_gizmo" ,
			"sv_icon_dot8_sml" ,
			"sv_icon_dot9_pix16_gizmo" ,
			"sv_icon_dot9_sml" ,
			"sv_icon_name0" ,
			"sv_icon_name1" ,
			"sv_icon_name2" ,
			"sv_icon_name3" ,
			"sv_icon_name4" ,
			"sv_icon_name5" ,
			"sv_icon_name6" ,
			"sv_icon_name7" ,
			"sv_icon_none" ,
			"sv_label_0" ,
			"sv_label_1" ,
			"sv_label_2" ,
			"sv_label_3" ,
			"sv_label_4" ,
			"sv_label_5" ,
			"sv_label_6" ,
			"sv_label_7" ,
			"SVN_AddedLocal" ,
			"SVN_Conflicted" ,
			"SVN_DeletedLocal" ,
			"SVN_Local" ,
			"SVN_LockedLocal" ,
			"SVN_OutOfSync" ,
			"tab_next" ,
			"tab_next@2x" ,
			"tab_prev" ,
			"tab_prev@2x" ,
			"tabbar on" ,
			"tabbar on f" ,
			"tabbar on f@2x" ,
			"tabbar on@2x" ,
			"TargetJoint2D Icon" ,
			"TE Toolbar" ,
			"TE toolbar button" ,
			"TE toolbar button act" ,
			"TE toolbar button act@2x" ,
			"TE toolbar button@2x" ,
			"TE toolbar dropdown act" ,
			"TE toolbar dropdown act@2x" ,
			"TE toolbar dropdown@2x" ,
			"TE Toolbar@2x" ,
			"Terrain Icon" ,
			"TerrainCollider Icon" ,
			"TerrainData Icon" ,
			"TerrainInspector.TerrainToolLower" ,
			"TerrainInspector.TerrainToolLower On" ,
			"TerrainInspector.TerrainToolLowerAlt" ,
			"TerrainInspector.TerrainToolPlants" ,
			"TerrainInspector.TerrainToolPlants On" ,
			"TerrainInspector.TerrainToolPlantsAlt" ,
			"TerrainInspector.TerrainToolPlantsAlt On" ,
			"TerrainInspector.TerrainToolRaise" ,
			"TerrainInspector.TerrainToolRaise On" ,
			"TerrainInspector.TerrainToolSculpt" ,
			"TerrainInspector.TerrainToolSculpt On" ,
			"TerrainInspector.TerrainToolSetheight" ,
			"TerrainInspector.TerrainToolSetHeight" ,
			"TerrainInspector.TerrainToolSetheight On" ,
			"TerrainInspector.TerrainToolSetheightAlt" ,
			"TerrainInspector.TerrainToolSetheightAlt On" ,
			"TerrainInspector.TerrainToolSettings" ,
			"TerrainInspector.TerrainToolSettings On" ,
			"TerrainInspector.TerrainToolSmoothHeight" ,
			"TerrainInspector.TerrainToolSmoothHeight On" ,
			"TerrainInspector.TerrainToolSplat" ,
			"TerrainInspector.TerrainToolSplat On" ,
			"TerrainInspector.TerrainToolSplatAlt" ,
			"TerrainInspector.TerrainToolSplatAlt On" ,
			"TerrainInspector.TerrainToolTrees" ,
			"TerrainInspector.TerrainToolTrees On" ,
			"TerrainInspector.TerrainToolTreesAlt" ,
			"TerrainInspector.TerrainToolTreesAlt On" ,
			"TestFailed" ,
			"TestIgnored" ,
			"TestInconclusive" ,
			"TestNormal" ,
			"TestPassed" ,
			"TestStopwatch" ,
			"Text Icon" ,
			"TextAsset Icon" ,
			"TextField" ,
			"TextField focused" ,
			"TextField focused@2x" ,
			"TextField@2x" ,
			"TextfieldDropdownAct" ,
			"TextFieldDropDownFocused" ,
			"TextFieldDropDownText" ,
			"TextMesh Icon" ,
			"Texture Icon" ,
			"Texture2D Icon" ,
			"Tile Icon" ,
			"Tilemap Icon" ,
			"TilemapCollider2D Icon" ,
			"TilemapRenderer Icon" ,
			"TimelineAsset Icon" ,
			"TimelineClipBG" ,
			"TimelineClipFG" ,
			"TimelineDigIn" ,
			"TimelineEditModeMixOFF" ,
			"TimelineEditModeMixON" ,
			"TimelineEditModeReplaceOFF" ,
			"TimelineEditModeReplaceON" ,
			"TimelineEditModeRippleOFF" ,
			"TimelineEditModeRippleON" ,
			"TimelineSelector" ,
			"toggle act@2x" ,
			"toggle focus@2x" ,
			"Toggle Icon" ,
			"toggle mixed act" ,
			"toggle mixed act@2x" ,
			"toggle mixed focus@2x" ,
			"toggle mixed@2x" ,
			"toggle on act" ,
			"toggle on act@2x" ,
			"toggle on focus@2x" ,
			"toggle on@2x" ,
			"toggle@2x" ,
			"ToggleGroup Icon" ,
			"Toolbar" ,
			"toolbar back" ,
			"toolbar back@2x" ,
			"toolbar button" ,
			"toolbar button act" ,
			"toolbar button act on" ,
			"toolbar button act on@2x" ,
			"toolbar button act@2x" ,
			"toolbar button on" ,
			"toolbar button on@2x" ,
			"toolbar button@2x" ,
			"Toolbar Minus" ,
			"Toolbar Plus" ,
			"Toolbar Plus More" ,
			"toolbar popup act" ,
			"toolbar popup act@2x" ,
			"toolbar popup@2x" ,
			"toolbar pulldown" ,
			"toolbar pulldown act" ,
			"toolbar pulldown act@2x" ,
			"toolbar pulldown@2x" ,
			"Toolbar@2x" ,
			"toolbarsearch focused" ,
			"toolbarsearch focused@2x" ,
			"toolbarsearch@2x" ,
			"toolbarsearchCancelButton@2x" ,
			"toolbarsearchCancelButtonActive" ,
			"toolbarsearchCancelButtonActive@2x" ,
			"toolbarsearchCancelButtonOff" ,
			"toolbarsearchCancelButtonOff@2x" ,
			"toolbarsearchpopup focused" ,
			"toolbarsearchpopup focused@2x" ,
			"toolbarsearchpopup@2x" ,
			"ToolHandleCenter" ,
			"ToolHandleGlobal" ,
			"ToolHandleLocal" ,
			"ToolHandlePivot" ,
			"Torso" ,
			"TouchInputModule Icon" ,
			"TrackedPoseDriver Icon" ,
			"TrailRenderer Icon" ,
			"tranp" ,
			"Transform Icon" ,
			"TransformTool" ,
			"TransformTool On" ,
			"transparent" ,
			"transparent@2x" ,
			"tree_icon" ,
			"tree_icon_branch" ,
			"tree_icon_branch_frond" ,
			"tree_icon_frond" ,
			"tree_icon_leaf" ,
			"TreeEditor.AddBranches" ,
			"TreeEditor.AddLeaves" ,
			"TreeEditor.Branch" ,
			"TreeEditor.Branch On" ,
			"TreeEditor.BranchFreeHand" ,
			"TreeEditor.BranchFreeHand On" ,
			"TreeEditor.BranchRotate" ,
			"TreeEditor.BranchRotate On" ,
			"TreeEditor.BranchScale" ,
			"TreeEditor.BranchScale On" ,
			"TreeEditor.BranchTranslate" ,
			"TreeEditor.BranchTranslate On" ,
			"TreeEditor.Distribution" ,
			"TreeEditor.Distribution On" ,
			"TreeEditor.Duplicate" ,
			"TreeEditor.Geometry" ,
			"TreeEditor.Geometry On" ,
			"TreeEditor.Leaf" ,
			"TreeEditor.Leaf On" ,
			"TreeEditor.LeafFreeHand" ,
			"TreeEditor.LeafFreeHand On" ,
			"TreeEditor.LeafRotate" ,
			"TreeEditor.LeafRotate On" ,
			"TreeEditor.LeafScale" ,
			"TreeEditor.LeafScale On" ,
			"TreeEditor.LeafTranslate" ,
			"TreeEditor.LeafTranslate On" ,
			"TreeEditor.Material" ,
			"TreeEditor.Material On" ,
			"TreeEditor.Refresh" ,
			"TreeEditor.Trash" ,
			"TreeEditor.Wind" ,
			"TreeEditor.Wind On" ,
			"UIR Shader Info 2" ,
			"UIR Shader Info 5" ,
			"UIR Shader Info 8" ,
			"UnityAttenuation" ,
			"UnityBlack" ,
			"UnityDefault2D" ,
			"UnityDitherMask" ,
			"UnityDitherMask2D" ,
			"UnityEditor.AnimationWindow" ,
			"UnityEditor.ConsoleWindow" ,
			"UnityEditor.DebugInspectorWindow" ,
			"UnityEditor.FindDependencies" ,
			"UnityEditor.GameView" ,
			"UnityEditor.Graphs.AnimatorControllerTool" ,
			"UnityEditor.HierarchyWindow" ,
			"UnityEditor.InspectorWindow" ,
			"UnityEditor.LookDevView" ,
			"UnityEditor.ProfilerWindow" ,
			"UnityEditor.SceneHierarchyWindow" ,
			"UnityEditor.SceneView" ,
			"UnityEditor.Timeline.TimelineWindow" ,
			"UnityEditor.VersionControl" ,
			"UnityGrayscaleRamp" ,
			"UnityGrey" ,
			"UnityGUIClip" ,
			"UnityHalo" ,
			"UnityLinearGrey" ,
			"UnityLogo" ,
			"UnityLogoLarge" ,
			"UnityNHxRoughness" ,
			"UnityNormalMap" ,
			"UnityRandomRotation" ,
			"UnityRed" ,
			"UnityWhite" ,
			"unselected" ,
			"unselected@2x" ,
			"UpArrow" ,
			"UserDefinedTargetBuildingBehaviour Icon" ,
			"UssScript Icon" ,
			"UxmlScript Icon" ,
			"vcs_add" ,
			"vcs_branch" ,
			"vcs_change" ,
			"vcs_check" ,
			"vcs_delete" ,
			"vcs_document" ,
			"vcs_edit" ,
			"vcs_incoming" ,
			"vcs_integrate" ,
			"vcs_local" ,
			"vcs_lock" ,
			"vcs_refresh" ,
			"vcs_sync" ,
			"vcs_unresolved" ,
			"vcs_update" ,
			"VerticalLayoutGroup Icon" ,
			"VerticalSplit" ,
			"VideoClip Icon" ,
			"VideoEffect Icon" ,
			"VideoPlayer Icon" ,
			"ViewToolMove" ,
			"ViewToolMove On" ,
			"ViewToolOrbit" ,
			"ViewToolOrbit On" ,
			"ViewToolZoom" ,
			"ViewToolZoom On" ,
			"VirtualButtonBehaviour Icon" ,
			"VisibilityOff" ,
			"VisibilityOn" ,
			"VisualEffect Gizmo" ,
			"VisualEffect Icon" ,
			"VisualEffectAsset Icon" ,
			"VisualTreeAsset Icon" ,
			"VuforiaBehaviour Icon" ,
			"VuMarkBehaviour Icon" ,
			"VUMeterTextureHorizontal" ,
			"VUMeterTextureVertical" ,
			"WaitSpin00" ,
			"WaitSpin01" ,
			"WaitSpin02" ,
			"WaitSpin03" ,
			"WaitSpin04" ,
			"WaitSpin05" ,
			"WaitSpin06" ,
			"WaitSpin07" ,
			"WaitSpin08" ,
			"WaitSpin09" ,
			"WaitSpin10" ,
			"WaitSpin11" ,
			"WelcomeScreen.AssetStoreLogo" ,
			"WelcomeScreen.MainHeader" ,
			"WelcomeScreen.UnityAnswersLogo" ,
			"WelcomeScreen.UnityBasicsLogo" ,
			"WelcomeScreen.UnityForumLogo" ,
			"WelcomeScreen.VideoTutLogo" ,
			"WheelCollider Icon" ,
			"WheelJoint2D Icon" ,
			"white" ,
			"winbtn_graph" ,
			"winbtn_graph_close_h" ,
			"winbtn_graph_max_h" ,
			"winbtn_graph_min_h" ,
			"winbtn_mac_close" ,
			"winbtn_mac_close_a" ,
			"winbtn_mac_close_h" ,
			"winbtn_mac_inact" ,
			"winbtn_mac_max" ,
			"winbtn_mac_max_a" ,
			"winbtn_mac_max_h" ,
			"winbtn_mac_min" ,
			"winbtn_mac_min_a" ,
			"winbtn_mac_min_h" ,
			"winbtn_win_close" ,
			"winbtn_win_close_a" ,
			"winbtn_win_close_h" ,
			"winbtn_win_max" ,
			"winbtn_win_max_a" ,
			"winbtn_win_max_h" ,
			"winbtn_win_min" ,
			"winbtn_win_min_a" ,
			"winbtn_win_min_h" ,
			"winbtn_win_rest" ,
			"winbtn_win_rest_a" ,
			"winbtn_win_rest_h" ,
			"window back" ,
			"window back@2x" ,
			"WindZone Gizmo" ,
			"WindZone Icon" ,
			"WireframeBehaviour Icon" ,
			"WorldAnchor Icon" ,
			"YUGOTHB Atlas" ,
			"YUGOTHR Atlas" ,
			"ヒラギノ角ゴシック W3 Atlas" ,
			"ヒラギノ角ゴシック W6 Atlas" ,
		};

		#endregion
	}
}
